[package]
name = "fp2"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alg_traits = { path = "../../algebra/alg_traits" }

[dev-dependencies]
test-case = "1.0.0"
assert-impl = "0.1.3"
