[package]
name = "polynominal"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
type_traits = { path = "../type_traits" }
dbg = { path = "../dbg" }

[dev-dependencies]
assert-impl = "0.1.3"
fp = { path = "../fp" }
