[package]
name = "query_test"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "query_test_union_find"
crate-type = ["staticlib"]

[dependencies]
rand = "0.7.3"
