[package]
name = "segtree"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
itertools = "0.10.1"
rand = "0.8.4"
randtools = { path = "../../utils/randtools" }
