[workspace]
members = [
    'crates/ac-adapter-rs',
    'crates/utils/*',
    'crates/string/*',
    'crates/algolib/*',
    'crates/range-query/*',
    'crates/algebra/*',
    'crates/numbers/*',
    'crates/geometry/*',
    'crates/test_tools/*',
]
