[workspace]
members = [
    'crates/ac-adapter-rs',
    'crates/utils/*',
    'crates/string/*',
    'crates/algolib/*',
    'crates/range-query/*',
    'crates/math/*',
    'crates/geometry/*',
    'crates/network-flow/*',
]
