[workspace]
members = [
    'crates/ac-adapter-rs',
    'crates/disjoint_set/*',
    'crates/fp/*',
    'crates/utils/*',
    'crates/string/*',
    'crates/algolib/*',
    'crates/range-query/*',
    'crates/math/*',
    'crates/geometry/*',
    'crates/flow/*',
]
