[config]
default_to_workspace = false

[tasks.pre-docs]
script = '''
cargo run --bin snippetter
cp contents/* target/doc
'''

[tasks.docs]
env = { RUSTDOCFLAGS = "--html-in-header contents/header.html" }
command = "cargo"
args = ["doc", "--workspace", "--no-deps"]
dependencies = ["pre-docs"]
