[config]
default_to_workspace = false

[tasks.pre-docs]
script = '''
cargo run --bin snippetter
cp contents/* target/doc
'''

[tasks.docs]
env = { RUSTDOCFLAGS = "--html-in-header contents/header.html" }
command = "cargo"
args = ["doc", "--workspace", "--no-deps"]
dependencies = ["pre-docs"]

[tasks.pedantics]
script = '''
cargo clippy --all-targets --all-features -- -W clippy::pedantic 2>&1 | grep 'note: `-W clippy::' | sed -n 's/.*note: `-W clippy::\([a-z|-]*\).*/\1/p' | sort | uniq
'''

[tasks.clippy]
command = "cargo"
args = [
  "clippy",
  "--all-features",
  "--all-targets",
  "--",
  "-W",
  "clippy::pedantic",
  "-A",
  "clippy::cast-possible-truncation",
  "-A",
  "clippy::cast-possible-wrap",
  "-A",
  "clippy::cast-precision-loss",
  "-A",
  "clippy::cast-sign-loss",
  "-A",
  "clippy::doc-markdown",
  "-A",
  "clippy::manual-let-else",
  "-A",
  "clippy::manual-clamp",
  "-A",
  "clippy::maybe-infinite-iter",
  "-A",
  "clippy::missing-const-for-fn",
  "-A",
  "clippy::missing-errors-doc",
  "-A",
  "clippy::missing-panics-doc",
  "-A",
  "clippy::module-name-repetitions",
  "-A",
  "clippy::must-use-candidate",
  "-A",
  "clippy::non-ascii-literal",
  "-A",
  "clippy::return-self-not-must-use",
  "-A",
  "clippy::shadow-unrelated",
  "-A",
  "clippy::semicolon-if-nothing-returned",
  "-A",
  "clippy::similar-names",
  "-A",
  "clippy::use-self",
  "-A",
  "clippy::uninlined-format-args",
]
