[package]
name = "test_vector"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.query_test]
git = "https://github.com/ngtkana/query_test.git"
tag = "v0.2.0"
package = "query_test"

[dependencies]
alg_traits = { path = "../../algebra/alg_traits" }
queries = { path = "../queries" }
rand = "0.7.3"
