[package]
name = "snippetter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
once_cell = "1.17.1"
toml = "0.7.3"
