[package]
name = "segtree2"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alg_traits = { path = "../../algebra/alg_traits" }
open = { path = "../../utils/open" }

[dev-dependencies.query_test]
git = "https://github.com/ngtkana/query_test.git"
branch = "main"
package = "query_test"

[dev-dependencies]
fp2 = { path = "../../utils/fp2" }
test_vector2 = { path = "../../test_tools/test_vector2" }
yosupo = { path = "../../test_tools/yosupo" }
alg_inversion_number = { path = "../../algebra/alg_inversion_number" }
ngtio = { path = "../../utils/ngtio" }
rand = "0.7.3"
