[package]
name = "segtree2"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.query_test]
git = "https://github.com/ngtkana/query_test.git"
branch = "main"
package = "query_test"

[dependencies]
rand = "0.7.3"

[dev-dependencies]
assert-impl = "0.1.3"
