[package]
name = "scc"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbg = { path = "../../utils/dbg" }

[dev-dependencies]
test-case = { git = "https://github.com/frondeus/test-case.git", branch = "master" }
rand = "0.7.3"

