[package]
name = "hungarian"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
approx = "0.4.0"
assert_that = "0.1.2"
dbg = { path = "../../utils/dbg" }
itertools = "0.10.0"
next_permutation = { path = "../../utils/next_permutation/" }
rand = "0.8.3"
test-case = "1.1.0"
