[package]
name = "test_vector"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
query_test_2 = { path = "../query_test_2" }
type_traits = { path = "../type_traits" }
