[package]
name = "test_vector2"
version = "0.1.0"
authors = ["ngtkana <ngtkana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.query_test]
git = "https://github.com/ngtkana/query_test.git"
branch = "main"
package = "query_test"

[dependencies]
type_traits2 = { path = "../type_traits2" }
queries2 = { path = "../queries2" }
rand = "0.7.3"
