name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy --all-targets

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test

  run-ignored-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Install python libraries
      run: pip3 install -r library-checker-problems/requirements.txt

    - name: Run ignored tests
      run: cargo test -- --nocapture --ignored
