name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: |
        cargo clippy --all-targets -- \
        -W clippy::pedantic \
        -W clippy::nursery \
        -A clippy::cast-possible-truncation \
        -A clippy::cast-possible-wrap \
        -A clippy::cast-precision-loss \
        -A clippy::cast-sign-loss \
        -A clippy::doc-markdown \
        -A clippy::filter-map \
        -A clippy::manual-let-else \
        -A clippy::maybe-infinite-iter \
        -A clippy::missing-const-for-fn \
        -A clippy::missing-panics-doc \
        -A clippy::module-name-repetitions \
        -A clippy::must-use-candidate \
        -A clippy::non-ascii-literal \
        -A clippy::shadow-unrelated \
        -A clippy::similar-names \
        -A clippy::use-self \

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo-doc
      run: cargo doc --workspace --no-deps
      env:
        RUSTDOCFLAGS: --html-in-header contents/header.html

    - name: Run the binary `snippetter`.
      run: cargo run --bin snippetter

    - name: Add index.html etc
      run: cp -r contents/* target/doc

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc

