name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Run makers:
  - name: Install cargo-make
    uses: actions-rs/cargo@v1
    with:
      command: install
      args: --debug cargo-make

  - name: Run CI
    uses: actions-rs/cargo@v1
    with:
      command: make
      args: ci-flow

  Deploy GitHub Pages:
    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc

