name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Run makers clippy
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: clippy

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Run makers test
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Run makers docs
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: docs
    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/docs

