name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: |
        cargo clippy --all-targets -- -W clippy::pedantic \
        -A clippy::must_use_candidate \
        -A clippy::non_ascii_literal \
        -A clippy::cast-sign-loss \
        -A clippy::doc_markdown \
        -A clippy::cast_possible_wrap \
        -A clippy::cast_possible_truncation \
        -A clippy::cast_precision_loss \
        -A clippy::module_name_repetitions \
        -A clippy::shadow_unrelated \
        -A clippy::maybe_infinite_iter \
        -A clippy::filter_map \
        -A clippy::similar_names

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo-doc
      run: cargo doc
