name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: clippy

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo-doc
      run: cargo doc --workspace --no-deps
      env:
        RUSTDOCFLAGS: --html-in-header contents/header.html

    - name: Run the binary `snippetter`.
      run: cargo run --bin snippetter

    - name: Add index.html etc
      run: cp -r contents/* target/doc

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc

