name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test

  run-ignored-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
          submodules: true  # v1 にしかないオプション
    - name: Generate point_add_range_sum
      run: python3 library-checker-problems/generate.py -p point_add_range_sum
    - name: Run ignored tests
      run: cargo test -- --nocapture --ignored
